# Generated by Django 4.0.4 on 2022-05-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
