# Generated by Django 4.0.4 on 2022-05-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_user_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
